<?php
extract( View::getVar() );
?>
<aside class="col s0 m4 l3">
    <ul class="collection with-header">
        <li class="collection-header">
            <?php View::partial('filter', false, ['filter'=>'.filtered']); ?>
        </li>
        <?php foreach ($items as $grimorio=>$a) : ?>
            <li class="collection-header filtered"><h4 class="blue-text text-darken-1"><?=$grimorio?>/</h4></li>
            <?php foreach ($a as $o) :
                $disabled = ($o->estado == '[PENDIENTE]') ? ' grey-text italic' : '' ?>
                <li class="box-link collection-item filtered<?=$disabled?>">
                    <?=$o->nombre?>
                    <a href="/hechizos/read/<?=$o->slug?>"></a>
                </li>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </ul>
</aside>
