
<div class="navbar-fixed">
    <div class="navbar-padding">
        <nav class="blue darken-1 center-align">
            <div class="max-width">
                <div class="col s1 m0 l0">
                    <a data-toggle-aside="aside">
                        <i class="material-icons">menu</i>
                    </a>
                </div>
                <h1 class="left ml15 mv15 "><a href="/">Tu grimorio</a></h1>
                <h2 class="left ml5 mv15 s0">— Código OK para copiar y pegar.</h2>
            </div>
        </nav>
    </div>
</div>
