<!DOCTYPE html>
<html>
    <head>
        <link href="/css/prism.css" rel="stylesheet" />
        <link href="/css/material-icons.css" rel="stylesheet">
        <link href="/css/materialize.min.css" rel="stylesheet">
        <link href="/css/hacks.css" rel="stylesheet">
        <link href="/css/helpers.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>
            <?php if ( ! empty($item->id) ) {
                echo "$item->grimorio :: $item->nombre";
            } else {
                echo "Tu grimorio: $controller_name :: $action_name";
            } ?>
        </title>
    </head>
    <body class="row" id="important">

        <?php View::partial('nav'); ?>

        <?php View::content(); ?>
        
        <?php View::partial('footer'); ?>

        <div class="modal pa15"></div>

        <script src="/js/jquery-3.1.1.min.js"></script>
        <script src="/js/prism.js"></script>
        <script src="/js/materialize.min.js"></script>
        <script src="/js/function.js"></script>
        <script src="/js/script.js"></script>
        <?=Js::inc()?>
    </body>
</html>
