
<form action="/" method="post">
    <h3 class="col s12">Escribe tu hechizo en un pergamino</h3>

    <?php View::partial('form', false, ['skip'=>array('id')]); ?>

    <div class="col s12 right-align">
        <button type="submit" class="btn green darken-1" name="hechizos" value="crear">Crear</button>
        <?php if ( ! empty($item->id) ) : ?>
            <a class="btn blue darken-1" href="/index/index/<?=$item->id?>">Ver</a>
            <button type="submit" class="btn orange darken-1" name="hechizos" value="editar">Editar</button>
            <button type="submit" class="btn red darken-1" name="hechizos" value="eliminar">Eliminar</button>
        <?php endif; ?>
    </div>
    <?php if ( ! empty($item->id) ) : ?>
        <input type="hidden" name="id" value="<?=$item->id?>">
    <?php endif; ?>
</form>
