
<div class="col s0 m4 l3">
    <ul class="collection with-header">
        <?php foreach ($items as $grimorio=>$a) : ?>
            <li class="collection-header"><h4><?=$grimorio?>/</h4></li>
            <?php foreach ($a as $o) : ?>
                <li class="box-link collection-item">
                    <?=$o->nombre?>
                    <a href="/index/index/<?=$o->id?>"></a>
                </li>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </ul>
</div>

<div class="col s12 m8 l9">
    <ul class="collection mr50">
        <li class="collection-item">
            <label>Grimorio</label>
            <?=$item->grimorio?>
        <li>
        <li class="collection-item">
            <label>Capitulo</label>
            <?=$item->capitulo?>
        </li>
        <li class="collection-item">
            <label>Nombre</label>
            <?=$item->nombre?>
        </li>
        <li class="collection-item">
            <label>Descripción</label>
            <?=$item->descripcion?>
        </li>
        <li class="collection-item">
            <label>Códigp</label>
            <pre class="line-numbers"><code class="language-php"><?=$item->codigo?></code></pre>
        </li>
        <li class="collection-item">
            <label>Autor</label>
            <?=$item->autor?>
        </li>
    </ul>
</div>

<?php if ( ! empty($item->id) ) : ?>
    <div class="actions">
        <a class="btn-floating load-modal orange darken-1" href="/index/formulario/<?=$item->id?>">
            <i class="material-icons">edit</i>
        </a>
    </div>
<?php endif; ?>
